CREATE FUNCTION UUID_TO_BIN (_uuid BINARY(36)) RETURNS BINARY(16) LANGUAGE SQL DETERMINISTIC CONTAINS SQL SQL SECURITY INVOKER RETURN UNHEX (
    CONCAT (
        SUBSTRING(_uuid, 15, 4),
        SUBSTRING(_uuid, 10, 4),
        SUBSTRING(_uuid, 1, 8),
        SUBSTRING(_uuid, 20, 4),
        SUBSTRING(_uuid, 25)
    )
);

CREATE FUNCTION UUID_FROM_BIN (_bin BINARY(16)) RETURNS BINARY(36) LANGUAGE SQL DETERMINISTIC CONTAINS SQL SQL SECURITY INVOKER RETURN LCASE (
    CONCAT_WS (
        '-',
        HEX (SUBSTRING(_bin, 5, 4)),
        HEX (SUBSTRING(_bin, 3, 2)),
        HEX (SUBSTRING(_bin, 1, 2)),
        HEX (SUBSTRING(_bin, 9, 2)),
        HEX (SUBSTRING(_bin, 11))
    )
);