root = "."
testdata_dir = "testdata"
tmp_dir = ".tmp"

[build]
  bin = "./.tmp/frontend/web"
  cmd = "go build -o ./.tmp/frontend/web frontend/web/main.go"
  delay = 1000
  exclude_dir = [".git", ".vscode", ".tmp", "docs", "databases", "background", "frontend/react", "frontend/api"]
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[log]
# Show log time
time = true
# Only show main log (silences watcher, build, runner)
main_only = false
# silence all logs produced by air
silent = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true